[tox]
requires =
    tox>=4
env_list = format, flake8, type, py

[testenv]
description = run package tests
usedevelop = true
deps =
    -e ../dawnpy
    pytest
    pytest-mock
    pytest-sugar
commands =
    pytest {posargs}

[testenv:format]
description = run code formatters
skip_install = true
deps =
    isort
    black
commands =
    isort {posargs:src/dawnpy_udp tests}
    black {posargs:src/dawnpy_udp tests}

[testenv:flake8]
description = run flake8
skip_install = true
deps =
    -e ../dawnpy
    flake8
    flake8-bugbear
    flake8-builtins
    flake8-walrus
    flake8-docstrings>=1.3.1
    pep8-naming
commands =
    flake8 --jobs 1 {posargs:src/dawnpy_udp tests}

[testenv:type]
description = run type checks
sitepackages = true
skip_install = true
deps =
    -e ../dawnpy
    mypy
commands =
    python -m mypy --strict --pretty {posargs:src/dawnpy_udp}

[pytest]
testpaths = tests
pythonpath = .
norecursedirs = .git .* *.egg* dist build
addopts = -rw
filterwarnings = error

[flake8]
per-file-ignores =
    tests/*: D
ignore =
    E203 W503
